version = 0.1

[default.deploy.parameters]
stack_name = "uk-garden-bird-classifier-app"
resolve_s3 = true
s3_prefix = "uk-garden-bird-classifier-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
